# Generated by Django 3.0.4 on 2020-03-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cashbox', models.DecimalField(decimal_places=2, max_digits=9)),
                ('withdraw', models.DecimalField(decimal_places=2, max_digits=9)),
                ('remain', models.DecimalField(decimal_places=2, max_digits=9)),
                ('sale', models.DecimalField(decimal_places=2, max_digits=9)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=9)),
                ('neto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('expense', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
