# Generated by Django 3.0.4 on 2020-03-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nitishop', '0002_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='total_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='total_neto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='total_sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
